CREATE TABLE datos_colaboradores (
  id_colaborador INTEGER PRIMARY KEY,
  nombre_completo TEXT,
  puesto TEXT,
  id_centro_costos INTEGER,
  centro_costos TEXT,
  id_departamento INTEGER,
  departamento TEXT,
  id_ubicacion INTEGER,
  ubicacion TEXT,
  plaza TEXT,
  regional TEXT,
  regional_hr TEXT,
  status_colaborador TEXT,
  fecha_entrada_puesto DATE,
  fecha_baja DATE,
  fecha_ultimo_dia_laborado DATE,
  causa_baja TEXT,
  motivo_baja TEXT,
  fecha_nacimiento DATE,
  estado_civil TEXT,
  genero TEXT,
  area_personal TEXT,
  area_cobranza TEXT,
  tipo_reclutamiento TEXT,
  tipo_contrato TEXT,
  uniforme TEXT,
  nivel_gestion TEXT
);