CREATE TABLE sanciones (
  id_key INTEGER PRIMARY KEY AUTOINCREMENT,
  id_colaborador INTEGER,
  nombre TEXT,
  antiguedad_meses REAL,
  antiguedad_years REAL,
  id_sancion INTEGER,
  fecha_solicitud DATE,
  clasificacion_sancion TEXT,
  motivo_sancion TEXT,
  detalle_sancion TEXT,
  descripcion_breve TEXT,
  acta_hechos BOOLEAN,
  causa_sancion TEXT,
  solicitado_por TEXT,
  analista_rl TEXT,
  tipo_sancion TEXT,
  dias_suspension INTEGER,
  fecha_aprobacion DATE
);